
name: Release_build_D_Version_Lock_limit_release

on:
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: relase_build
    
jobs:
  iot2050_debian-example-image_lock:
    name: example image Lock
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: sr2-develop
      - name: Build image
        run: git tag  D01.00.00.10 HEAD && ./kas-container build  kas-iot2050-example.yml:kas/opt/tisdk-2020.01.yml 2>&1 | tee -a ./build_example-image.log
      - name: Upload image
        uses: actions/upload-artifact@v2
        with:
          name: iot2050-example-image
          path: build/tmp/deploy/images/iot2050/iot2050-image-example-iot2050-debian-iot2050.wic.img*
      - name: Upload example build log
        uses: actions/upload-artifact@v2
        with:
          name: iot2050-example-image-build-log
          path: ./build_example-image.log

  iot2050_debian-rt-example-image_lock:
    name: RT example image Lock
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: sr2-develop
      - name: Build RT image
        run: git tag  D01.00.00.10 HEAD && ./kas-container  build  kas-iot2050-example.yml:kas/opt/preempt-rt.yml:kas/opt/tisdk-2020.01.yml 2>&1 | tee -a ./build_RT-example-image.log
      - name: Upload image
        uses: actions/upload-artifact@v2
        with:
          name: iot2050-example-image-rt
          path: build/tmp/deploy/images/iot2050/iot2050-image-example-iot2050-debian-iot2050.wic.img*
      - name: Upload RT example build log
        uses: actions/upload-artifact@v2
        with:
          name: iot2050-example-image-RT-build-log
          path: ./build_RT-example-image.log
          
  iot2050-sdk_lock:
    name: SDK Lock
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: sr2-develop
      - name: Build SDK
        run: git tag  D01.00.00.10 HEAD && ./kas-container  build kas-iot2050-example.yml:kas/opt/sdk.yml:kas/opt/tisdk-2020.01.yml 2>&1 | tee -a  ./build_SDK.log && ls -l build/tmp/deploy/images/iot2050/
      - name: Archive sdk
        uses: actions/upload-artifact@v2
        with:
          name: iot2050-sdk
          path: build/tmp/deploy/images/iot2050/*.tar*
      - name: Upload sdk build log
        uses: actions/upload-artifact@v2
        with:
          name: iot2050-sdk-build-log
          path: ./build_SDK.log
          
  iot2050_bootloaders_lock:
    name: Bootloaders Lock
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: sr2-develop
      - name: Advanced
        run: git tag  D01.00.00.10 HEAD && ./kas-container  build kas-iot2050-boot-advanced.yml:kas/opt/tisdk-2020.01.yml 2>&1 | tee -a  ./build_advance_bootloader.log
      - name: Archive bootloaders
        uses: actions/upload-artifact@v2
        with:
          name: iot2050-bootloaders
          path: build/tmp/deploy/images/iot2050/*.bin
      - name: Archive build bootloader log
        uses: actions/upload-artifact@v2
        with:
          name: iot2050-bootloaders_build_log
          path: ./build*.log
